# Generated by Django 3.2.23 on 2023-11-03 11:24

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231103_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lohit/Desktop/Kartik_Project_Django/head/media'), verbose_name='Cover image'),
        ),
    ]
