# Generated by Django 3.2.23 on 2023-11-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231103_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.place'),
            preserve_default=False,
        ),
    ]
