# Generated by Django 3.2.23 on 2023-11-03 14:29

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nearby_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearby',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Museums', 'Museums'), ('Category 3', 'Category 3'), ('Category4', 'Category4')], default='', max_length=100, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearby',
            name='desc',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearby',
            name='img',
            field=models.ImageField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lohit/Desktop/Kartik_Project_Django/head/media'), verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='nearby',
            name='lat',
            field=models.CharField(default='', max_length=100, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nearby',
            name='long',
            field=models.CharField(default='', max_length=100, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
