# Generated by Django 3.2.23 on 2023-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231103_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='nearby_id',
            field=models.CharField(default='s', max_length=250, verbose_name='Slug'),
        ),
    ]
