# Generated by Django 3.2.23 on 2023-11-03 15:05

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_nearby_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img0',
            field=models.ImageField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lohit/Desktop/Kartik_Project_Django/head/media'), verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='img1',
            field=models.ImageField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lohit/Desktop/Kartik_Project_Django/head/media'), verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='img2',
            field=models.ImageField(null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lohit/Desktop/Kartik_Project_Django/head/media'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='nearby',
            name='category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Museums', 'Museums'), ('Speciality', 'Speciality'), ('Shop', 'Shop'), ('Home', 'Home')], max_length=100, verbose_name='Category'),
        ),
    ]
